### PR TITLE
Prepare for Python 3

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tseaver** [comment]
Until we can add tox/travis testing, I don't think we should actually be claiming explicit Python3 compatibility (in either the changelog or in Trove classifiers).

**Comment by tomgross** [comment]
Anything missing for this being merged?

**Comment by do3cc** [comment]
It is not tested against python3 yet

**Comment by tseaver** [comment]
@do3cc the PR no longer claims Py3k in anything but its title (which I will fix).

**Comment by tseaver** [comment]
Thanks for your efforts, @tomgross!

**Pull request merged**
