### PR TITLE
make ZServer a dependency for py2 only

### LINKED ISSUE #6: Improve the tests
Make the test work without the need to startup zope, see:
- https://github.com/zopefoundation/Products.SiteErrorLog/pull/4#issuecomment-374315506
- https://github.com/zopefoundation/Products.SiteErrorLog/blob/05e113fe5c7dc9917c837bdbeb4bfa22b593c041/src/Products/SiteErrorLog/tests/testSiteErrorLog.py#L26

### PR DESCRIPTION
**Pull request by pbauer**
Fixes #6

### CODE REVIEW

**Comment by ale-rt** [comment]
I wonder if we should just drop the requirement for all Python versions.
It seems ZServer is not used in the package at all:
```
[ale@emily Products.SiteErrorLog]$ grep -R ZServer
setup.py:        'ZServer',
```

**Comment by tseaver** [comment]
The (really ugly) `testSiteErrorLog` module imports `Zope2` and calls `Zope2.startup()` at *import time*, which fails if `ZServer` is not installed.

That *has* to be bogus:  no reasonable test needs to have the server running.

**Comment by icemac** [comment]
@hannosch Is this package intended to run with Zope 4 thus should it be ported to Python 3?

**Comment by icemac** [comment]
@ale-rt Running the test on Python 3.6 breaks with `ModuleNotFoundError: No module named 'ZServer'` as `Zope2.startup()` is actually `ZServer.Zope2.startup()`.

**Comment by ale-rt** [comment]
Oh, I see @icemac. 
So actually we can move this requirement to the `[test]` feature, even better fix the test to not use Zope2.startup().
Anyway it seems reasonable to me to merge this one

**Comment by tseaver** [comment]
I don't think we should merge as-is.  Instead, we should fix the stupid test which starts a server at import time, and remove the `ZServer` dependency altogether.

**Comment by icemac** [comment]
@tseaver Do you think this is mergeable after my fixes?

**Pull request merged**
