### PR TITLE
Fix #17: report traversal problems

### LINKED ISSUE #17: SiteErrorLog cannot report traversal problems
`SiteErrorLog` is integrated with Zope 4 via the `ZPublisher.interfaces.IPubFailure` handler `Products.SiteErrorLog.SiteErrorLog.IPubFailureSubsciber`. This does nothing unless the request object has `PUBLISHED` set. However, `PUBLISHED` is set only after a successful traversal. As a consequence, `SiteErrorLog` ignores all traversal problems.

### PR DESCRIPTION
**Pull request by d-maurer**

### CODE REVIEW

**Comment by icemac** [comment]
@dwt Do you think that you could review this PR?

**Comment by dwt** [comment]
Sorry, I'm late to the party, I should have time to look into this tomorrow.

**Comment by dwt** [comment]
I'm not sure I do have the context to say very meaningful things, but I'll try

**Comment by d-maurer** [comment]
?rekcäH nitraM? wrote at 2019-3-12 10:29 -0700:
>I'm not sure I do have the context to say very meaningful things, but I'll try

All extensions came from debugging Plone exceptions which have not been
reported by `error_log` -- either because the request lacked
`PUBLISHED` (set up only at the end of successful traversal)
or because the exception has been caused by a "method" (not directly
working together with acquisition).

**Comment by dwt** [comment]
This looks interesting, but is totally missing a unittest, that demonstrates the kind of errors this would catch. (And sorry, I don't really know the internals of zope well enough that I could provide one.)

**Comment by dwt** [comment]
Could you provide a test case that shows how this catches errors?

**Comment by d-maurer** [comment]
@dwt I have added tests.

Note, that the overall test setup seems broken (insufficient test isolation): In my test layer, I found not one but even two handler registrations for `IPubFailureSubscriber` already present (one might have been justified by the `ZopeLite` layer; but definitely, there should not be two).

**Review by dwt — APPROVED** [review]
LGTM, I can't really say that I understand all the internals of Zope that are used here, but at least the tests catch when the change is rolled back. So...

@icemac do you have any additional comments?

**Review by icemac — APPROVED** [review]
LGTM.

**Comment by icemac** [comment]
@d-maurer Should I cut a release of this package?

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-3-15 01:20 -0700:
>@d-maurer Should I cut a release of this package?

I think this would be a good idea:
hunting down the observed Plone problems with the (now fixed)
problems of "SiteErrorLog" has been a pain.
Those Plone problems are meanwhile fixed, but, nevertheless,
the `SiteErrorLog` fixes could simplify the analysis of some other problems.

**Comment by icemac** [comment]
@d-maurer Released to PyPI, see https://pypi.org/project/Products.SiteErrorLog/5.2/

**Pull request merged**
